#!/bin/bash
sudo yum update -y
sudo yum install git -y
sudo amazon-linux-extras install epel -y
sudo yum install stress -y
cd /
sudo git clone https://github.com/xiehuangjun/A3.git
cd A3/
sudo pip3 install -r requirements.txt
cd API/
sudo sed -i -e 's/host_value/[Database's endpoint]/g' -e 's/port_value/[Database's port]/g' -e 's/user_value/[Database's username]/g' -e 's/password_value/[Database's password]/g' config.ini
sudo yum install mysql-devel gcc python-pip python-devel -y
cd create_table
sudo python3 create_table.py
cd /
cd A3/API/
sudo python3 api.py
